powerbot/RSBot-API

- Crosshair.java
- Interactive.java
- rt4/Game.java
- rt4/Interactive.java
- rt6/Game.java
- rt6/Interactive.java
Added them and cleaned up documentation
> Crosshair interact methods

- rt4/CacheItemConfig.java
- rt4/GroundItem.java
- rt4/Item.java
Can you check Item.name()
RT6 can use Component#itemName() but that doesn't exist for RT4.
I'm not sure if using itemConfig will always work or if it should just always load from the cache.
Tested the class loading items 0-13352
> Added RT4 item definition from cache

- Actionable.java
- Drawable.java
- Identifiable.java
- Locatable.java
- MessageListener.java
- Nameable.java
- PaintListener.java
- Script.java
- Stackable.java
- TextPaintListener.java
- Textable.java
- Viewable.java
- rt4/BasicQuery.java
- rt4/Chat.java
- rt4/Menu.java
- rt4/PlayerQuery.java
- rt6/Chat.java
- rt6/GroundItemQuery.java
- rt6/HintArrowQuery.java
- rt6/MobileIdNameQuery.java
- rt6/Npcs.java
- rt6/PlayerQuery.java
- rt6/Players.java
- rt6/Projectiles.java
- rt6/Resizable.java
- rt6/Widgets.java
Completed the query documentation and renamed ambiguous parameters.
> Query Documentation

- src/sd8z/core/painter/Detail.java
- src/sd8z/core/painter/Painter.java
- src/sd8z/core/painter/SkillMonitor.java
- src/sd8z/core/script/Job.java
- src/sd8z/core/script/JobContainer.java
- src/sd8z/core/script/JobSet.java
- src/sd8z/core/script/Script.java
- src/sd8z/scripts/sbonfire/SBonfire.java
- src/sd8z/scripts/sbonfire/jobs/Bank.java
- src/sd8z/scripts/sbonfire/jobs/Bonfire.java
- src/sd8z/scripts/sbonfire/jobs/Pick.java
- src/sd8z/scripts/sbonfire/jobs/Spirit.java
- src/sd8z/scripts/sbonfire/util/GUI.java
- src/sd8z/scripts/sbonfire/util/Log.java
Let's hope I didn't fuck up this time.
> sBonfire 0.80

- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/DBWoodcutter.java
++ Support for switching at Yews at level 60
~ Better chopping methods - now turns to next tree in the vicinity
> Switching to Yews

- src/helicopter12/scripts/Elder.java
> Added Elder Log Collector

- rt4/Equipment.java
- rt6/Hud.java
> Avoids trying to open equipment tab if bank is open

- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/Components.java
- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/DBWoodcutter.java
- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/DBWoodcutterGUI.java
- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/Trade.java
++ More debugging in paint
++ gui
++ Mule Trade Support
> Add Mule Trading

- src/xXTheAwesomerXx/dbscripts/rs3/woodcutting/DBWoodcutter.java
Import was incorrectly packaged, removed.
> Fixed Import

- src/Leroux/FreeWorldChopper/Contants/Areas.java
- src/Leroux/FreeWorldChopper/Contants/Paths.java
- src/Leroux/FreeWorldChopper/Enums/Bankers.java
- src/Leroux/FreeWorldChopper/Enums/Trees.java
- src/Leroux/FreeWorldChopper/Methods/Walker.java
- src/Leroux/FreeWorldChopper/Script/FreeChopper.java
- src/Leroux/FreeWorldChopper/Script/GUI.java
- src/Leroux/FreeWorldChopper/Script/Task.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/Chop.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/Deposit.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/Drop.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/PowerChop.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/WalkToBank.java
- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/WalkToSpot.java
- src/Leroux/FreeWorldChopper/WoodCutting/Wrapper/WoodCutting.java
- src/Leroux/NewbHonies/methods/Walker.java
- src/Leroux/NewbHonies/script/NewbHonies.java
- src/Leroux/NewbHonies/tasks/Deposit.java
Fixed banking in NewbHonies
Releasing FreeWorld Chopper
> Fix and Script release

- src/Leroux/FreeWorldChopper/WoodCutting/Tasks/Deposit.java
- src/Leroux/NewbHonies/constants/InvItems.java
- src/Leroux/NewbHonies/script/NewbHonies.java
- src/Leroux/NewbHonies/tasks/Deposit.java
- src/Leroux/NewbHonies/tasks/GrabHonies.java
- src/Leroux/NewbHonies/tasks/Move_ToBank.java
- src/Leroux/NewbHonies/tasks/Move_ToField.java
Changed how move_tofield activates, the honeycomb id seemed to be
returning -1 intermittently so it would simply run back to the field
upon reaching the bank.
Added script status and time running to the paint.
> Minor changes

- rt4/Equipment.java
- rt4/Game.java
- rt4/Widget.java
Added https://github.com/powerbot/powerbot/issues/1178. If the equipment tab is not opened it will set item stack size to 1.
@Timer is it possible to parse stack sizes like in rt6? https://github.com/powerbot/powerbot/blob/rsbot-api/rt6/Equipment.java#L20
> RT4 Equipment parsing

- src/helicopter12/scripts/Elder.java
Changed variables names to become more descriptive.
Fixed broken-logic segments.
Improved randomization logic.
Removed some null-pointer bugs.
Switched from integer to enum state transitions.
> Readability and formatting consistency updates for Elder

- src/helicopter12/scripts/Elder.java
Reverted to old randomizing method as the new method was said to have issues with locked lodestones. Also added checks to the teleporting steps to ensure the widgets are clicked before proceeding. Otherwise, the script will just sit there.
> Elder update V2.02 - Randomization and teleport fixes

- src/helicopter12/scripts/Elder.java
*Fixed out of bounds exception that caused the script to stop running after it cycled once through all 4 locations.
*Added XP tracking to the paint and adjusted the paint to accommodate the new line of paint. 
*Added jujupotion ID for future reference
*Lowered anti-ban execution rate
> Elder update V2.03 - Out of Bound Exception Fix

- src/Leroux/FreeWorldCooker/Script/FreeWorldCooker.java
I had used commas instead of semicolons in the properties field of the
manifest, I believe that prevented the script from displaying properly
on the SDN
> Fixed Properties

- src/andyroo/FaladorAgility.java
http://www.powerbot.org/community/topic/1298690-agility/
> first commit

- src/andyroo/FaladorAgility.java
> fally agility 1.1

- src/andyroo/Antiban.java
- src/andyroo/FaladorAgility.java
i did a bunch of commands on git without knowing what im doing
> Fally Agility: v 1.3

- src/andyroo/Agility/Antiban.java
- src/andyroo/Agility/FaladorAgility.java
- src/andyroo/Agility/Obstacle.java
- src/andyroo/Antiban.java
- src/andyroo/FaladorAgility.java
- src/andyroo/Obstacle.java
reduced script size considerably with new logic 
checks energy level and toggles (to be tested)
> Fally Agility: v2.0

- Nameable.java
- rt4/Bank.java
- rt4/BasicQuery.java
- rt4/Constants.java
- rt4/ItemQuery.java
- rt4/PlayerQuery.java
- rt4/Prayer.java
- rt4/Varpbits.java
- rt6/GroundItemQuery.java
- rt6/ItemQuery.java
- rt6/MobileIdNameQuery.java
- rt6/PlayerQuery.java
Finished prayers, moved Prayer constants to Constants class, added varpbit helper methods.
> RT4 prayers and bank update

- src/andyroo/Agility/FaladorAgility.java
> renamed class FaladorAgility2 to FaladorAgility

- src/andyroo/Agility/FaladorAgility.java
still doesnt appear on sdn...hopefully this is the fix
> import Obstacle class

- rt4/Chat.java
- rt4/ChatOption.java
- rt4/Constants.java
- rt4/TextQuery.java
- rt6/Chat.java
Added ChatOption class and TextQuery to rt4, deprecated some chat methods and added some additional methods that match rt6 version of Chat class.
> Finished rt4 Chat

- src/andyroo/agility/FaladorAgility.java
- src/andyroo/blastfurnace/BarInfo.java
- src/andyroo/blastfurnace/BlastFurnace.java
Fally agility v2.2
paint progress
random camera at start point
Blast Furnace v 1.1
added steel bar
improved conveyor belt interaction
fixed bar widget close
smaller paint
> Falador Agility: added paint progress, random camera at start point | Blast Furnace: added steel bars

- src/helicopter12/scripts/simpleThiever.java
In development; User-testing required.. See thread in development section
> Initial Release of simpleThiever(In Development)

- src/andyroo/blastfurnace/BlastFurnace.java
v 1.3
now moves to bank if distance > 5 (instead of just in viewport)
now moves to belt if distance >= 5 (instead of just in viewport)
randomized camera movement (turnTo)
removed random npc handling
handles dialogue
> Blast furnace v 1.3: better movement, randomized cam movement, handles dialogue from misclicks

- src/andyroo/blastfurnace/BlastFurnace.java
> Blast furnace v 1.3a : fixed a bug that caused script to stop when adding ores

- src/andyroo/blastfurnace/BlastFurnace.java
* v 1.3c
* fixed some logic while moving to conveyor belt
* randomized camera turning decision
* handles case when attempting to deposit ores when furnace is full
* screenshot on script end
> Blast Furnace v1.3c : fixed logic with moving to conveyor belt that caused script to stop

- src/helicopter12/scripts/OSThiever.java
Cleaned somethings up and fixed the compile error.
> Fixed final error compile issue

- src/andyroo/blastfurnace/BlastFurnace.java
- src/andyroo/humidify/Humidify.java
- src/andyroo/util/Antiban.java
Blast furnace v 1.3d
adjusted bank and dispenser areas
fixed anti-idle triggering when bars were ready
Antiban
removed player right click, added npc right click
> Blast furnace v 1.3d : adjusted bank/dispenser areas, fixed anti-idle triggering when bars ready

- src/helicopter12/scripts/OSThiever.java
Added log uploading on script stop for analysis purposes and also added a simple anti-ban
> Added log uploading and a simple anti-ban

- src/autonomous/herblore/AutonomousHerblore.java
-Stored state in string for repaint
-Cached prices
-Moved download of image from repaint
-Slight changes to when/how image is downloaded
> Minor revisions which can for the most part be summed up on my project page

- src/helicopter12/scripts/OSThiever.java
Going from hard coded GUI menu to dynamic menu. Thief options are now completed.
> Added a semi-dynamic menu

- src/andyroo/blastfurnace/BlastFurnace.java
Blast Furnace v1.4:
pays foreman
keeps track of how many times foreman was paid
fixed a bug where expectedPrimary did not update
now initializes script properly when starting it from login screen
reduced bounds of conveyor belt
handles accidental reports
> Blast Furnace v 1.4a: foreman payment support

- src/andyroo/blastfurnace/BlastFurnace.java
v 1.4b
removed black background and change text color to black on gui
implemented report widget handler for real this time
fixed a bug where script failed to click foreman
> Blast Furnace v 1.4b: changed gui, finished implementing report handler, fixed bug with foreman

- src/andyroo/blastfurnace/BlastFurnace.java
v 1.4d
fixed a bug that repeatedly opens bank when attempting withdraw coins
removed useless setBarType function
code formatting
> Blast furnace v 1.4d: bug fix and code tidying

- src/andyroo/blastfurnace/BarInfo.java
- src/andyroo/blastfurnace/BlastFurnace.java
v 1.4e
fixed screenshot having a black background, hiding the black text
fixed bug where script attempted to click bank chest while bar widget was open
> Blast Furnace v 1.4e: fixed screenshot

- rt6/Constants.java
RS3 updated minimap components. Addresses issue #1319.
> Update Minimap Components

- src/autonomous/herblore/AutonomousHerblore.java
Modified antiban; Added logout on script stop; Moved time from state to repaint for more accurate time;
> Autonomous

- Input.java
- Textable.java
- Tile.java
- rt4/TileMatrix.java
- rt4/Varpbits.java
- rt4/Widget.java
- rt6/TileMatrix.java
- rt6/Varpbits.java
- rt6/Widget.java
Added more documentation because a lot of the API isn't documented yet. Also fixed a few typos in existing documentation.
> Add more documentation

- src/montezuma/script/RobsTutorialIsland.java
- src/montezuma/script/ScriptState.java
- src/montezuma/script/task/CastWindTask.java
- src/montezuma/script/task/ChopTask.java
- src/montezuma/script/task/CookDoughTask.java
- src/montezuma/script/task/CookShrimpTask.java
- src/montezuma/script/task/FishTask.java
- src/montezuma/script/task/LightFireTask.java
- src/montezuma/script/task/MakeDoughTask.java
- src/montezuma/script/task/OpenDoorTask.java
- src/montezuma/script/task/OreTask.java
- src/montezuma/script/task/SmeltBarTask.java
- src/montezuma/script/task/SmeltDaggerTask.java
- src/montezuma/script/task/TalkToGuideTask.java
- src/montezuma/script/task/Task.java
- src/montezuma/script/task/UseBankTask.java
- src/montezuma/script/task/VisitPollTask.java
I added in the source files for my tutorial island script
> adding my tutorial island

- src/outragehost/chicken/Antiban.java
- src/outragehost/chicken/Chicken.java
- src/outragehost/chicken/Chicken_Feathers.java
- src/outragehost/chicken/Gate.java
> Outrage Chicken Slayer: Updated AntiBan And Gate Detection

- rt4/Game.java
Quest tab can have different textures depending on what the user selected to show (minigames, achievement diary, etc...). This is rt4.
> Support for different textures for game tabs

- rt6/Constants.java
Fix magic values of backpack components. Fixes #1363.
> Update magic values for Backpack

- rt6/Constants.java
> Fix magic values for backpack (again)

- rt6/Hud.java
https://github.com/powerbot/powerbot/issues/1370
> Fixed Hud NPE

- src/is0lates/GrandExchangeAlcher/GrandExchangeAlcher.java
- src/is0lates/GrandExchangeAlcher/GrandExchangeAlcherForm.java
People having issues with my script. Changed some code.
> Grand Exchange Alcher: Fixed a few bugs.

- rt6/CacheItemConfig.java
This includes a new boolean to determine if the item is two-handed or not.
> Decoded second slot opcode

- src/mistermaru/CanifisAgilityCourse/CanifisAgilityCourse.java
- src/mistermaru/CanifisAgilityCourse/Enums/Gaps.java
- src/mistermaru/CanifisAgilityCourse/Task.java
- src/mistermaru/CanifisAgilityCourse/Tasks/ClimbTallTree.java
- src/mistermaru/CanifisAgilityCourse/Tasks/FallingFromCourse.java
- src/mistermaru/CanifisAgilityCourse/Tasks/JumpGap.java
- src/mistermaru/CanifisAgilityCourse/Tasks/JumpPole.java
- src/mistermaru/CanifisAgilityCourse/Tasks/TakeMarkOfGrace.java
Added a topic to the script and made some  changes in TakeMarkOfGrace.
> Added mistermaru/CanifisAgilityCourse

- src/is0lates/ChocolateDuster/ChocolateDuster.java
Forum Topic: https://www.powerbot.org/community/topic/1309466-chocolate-duster/
> Commited ChocolateDuster

- src/lugge/scripts/rs3/luckykebbit/LuckyKebbit.java
- src/lugge/scripts/rs3/luckykebbit/data/Path.java
- src/lugge/scripts/rs3/luckykebbit/data/Tiles.java
- src/lugge/scripts/rs3/luckykebbit/data/Tracks.java
- src/lugge/scripts/rs3/luckykebbit/task/Actions.java
- src/lugge/scripts/rs3/luckykebbit/task/Conditions.java
- src/lugge/scripts/rs3/luckykebbit/task/States.java
- src/lugge/scripts/rs3/luckykebbit/util/Paint.java
- src/lugge/scripts/rs3/luckykebbit/util/Time.java
first release of my polar kebbit hunter 
http://www.powerbot.org/community/topic/1309379-application-lugge-rs3-polar-kebbit-hunter/
> kebbit hunter release

- src/Richardluk12/aio_agility/AgilityTrainer.java
- src/Richardluk12/aio_agility/Course.java
- src/Richardluk12/aio_agility/FAIL.java
- src/Richardluk12/aio_agility/Obstacle.java
- src/Richardluk12/aio_agility/Timer.java
This is my first script I decided to release.
> Richardluk12's AIOAgility

- rt6/Constants.java
for the "not-so-high-priority" issue #1397
> Update constants for lobby

- src/Richardluk12/aio_agility/AgilityTrainer.java
- src/Richardluk12/aio_agility/Course.java
-Added logic for determining obstacle to avoid doing the wrong obstacle.
> Richardluk12's AIOAgility v2.01 update

- src/Richardluk12/aio_agility/AgilityTrainer.java
-Added some food
-Fixed some barbarian outpost delays
-Added turn randomization
-Changed getRuntime() to getTotalRuntime() for accurate xp/hr and laps/hr display.
> Richardluk12's AIOAgility Update v2.02

- src/superchaoran/BananaFiller/BananaFiller.java
http://www.powerbot.org/community/topic/1311553-rs3-banana-banana5-script-500kh-applying-for-scriptwriter/
> Banana->Banana(5) Script BananaFiller Topic ID 1311553

- rt6/CombatBar.java
https://github.com/powerbot/powerbot/issues/1042
> Added support for player effects

- rt4/Combat.java
> Special attack button is now found dynamically

- src/superchaoran/BananaFiller/BananaFiller.java
- src/superchaoran/GraniteSplitter/GraniteSpliterMain.java
- src/superchaoran/HerbsUlitimate/HerbsUltimateMain.java
- src/superchaoran/HerbsUlitimate/jobs/CleanHerb.java
- src/superchaoran/HerbsUlitimate/jobs/MakeUnfPotion.java
- src/superchaoran/RuneCrafting/ImprovedBank.java
- src/superchaoran/RuneCrafting/MistRun.java
- src/superchaoran/RuneCrafting/SmokeRun.java
Adding new topic: Smoke Rune runner
https://www.powerbot.org/community/topic/1313029-application-mist-rune-runner-1m-3mhr/
topic ID: 1313029
Updating, bugfixing previous script.
> Smoke Rune runner ID:1313029

- src/SirFancyGamer/scripts/OSGuardSlayer.java
Updated closed door object id so that player doesn't get stuck on the door.
> Update to Al Kharid warrior fighter

- src/org/powerbot/script/rt4/Constants.java
Added a new widget for level-up chat.
> Added a new widget for chat continue button rt4

- src/org/powerbot/script/rt4/Constants.java
- src/org/powerbot/script/rt4/Magic.java
- Added validity detection for Spells (which compares the current component's texture ID with the spell's natural "off" texture ID)
- Fixed Bones to Peaches and Earth Strike
- Added documentation
- Declared explicit access modifiers for constructors
- Added Ancient Magicks
- Future-proof component indexes
**Suggestions**
- ~~Perhaps add the "on" texture IDs so we don't have to rely on component IDs?~~ Done.
> Improve Magic Interface

- src/sd8z/scripts/sbonfire/SBonfire.java
- src/sd8z/scripts/sbonfire/jobs/Bonfire.java
Hiding instead of deleting since fix is easy I think, just widget change.
> hiding broken script, again again

- src/Fabhaz/GUI.java
- src/Fabhaz/JewelryCrafter.java
- src/Fabhaz/Resources.java
The one currently on the SDN is not working so i made my own.
> Added Jewerly Crafter

- src/org/powerbot/script/rt4/Constants.java
I came across an chat widget with click to continue but it wasn't supported, added it.
> new CHAT_CONTINUES widget

- src/org/powerbot/bot/rt6/DrawObjects.java
https://github.com/powerbot/powerbot/issues/1301
> Added mainId painting to DrawObjects and made it more efficient

- src/org/powerbot/script/rt6/Component.java
A potential freezing issue fix as explained in https://github.com/powerbot/powerbot/issues/1531.
> Potential freezing issue fix

- src/Noodleking/FishingLobsters.java
F2P Lobster catching script as requested on the forum
> Added Script

- src/Noodleking/FishingLobsters.java
changed banking location, and fixed several bugs
> Bugfixes and new banking place

- src/Noodleking/FishingLobsters.java
Opening the bank got removed in the last update. Now the opening is added and the banking is improved.
> Added improved banking

- src/Noodleking/FishingLobsters.java
There was a bug that the player got stuck onto the ship. At first it was rare, but then it happened every run. The code has been rewritten, en the bug is removed completely.
> Removed Ship bug

- src/Noodleking/FishingLobsters.java
Added ability to powerfish, keep or drop tuna, better inventory checking, and measurements to log out in some cases
> Added options

- src/ih_justin/zammywine/Bank.java
- src/ih_justin/zammywine/CHDLZammyWiner.java
- src/ih_justin/zammywine/Info.java
- src/ih_justin/zammywine/Task.java
- src/ih_justin/zammywine/Telegrab.java
- src/ih_justin/zammywine/WalkToBank.java
- src/ih_justin/zammywine/WalkToTemple.java
- src/ih_justin/zammywine/World.java
- src/ih_justin/zammywine/WorldHop.java
- src/ih_justin/zammywine/Worlds.java
Haven't completely implemented world hopping. Will be randomizing bank usage soon.
> Initial zammy wine commit

- src/Ryzzoa/rSalamanders/GUI.java
- src/Ryzzoa/rSalamanders/rSalamanders.java
Release feature is built, but wont be implemented til backpack is fixed.
> Initial commit

- src/SaiyanKunt/chickenKiller/BuryBones.java
- src/SaiyanKunt/chickenKiller/ChickenKiller.java
- src/SaiyanKunt/chickenKiller/ChickenKillerGUI.java
- src/SaiyanKunt/chickenKiller/GenericOSRSTask.java
- src/SaiyanKunt/chickenKiller/KillChicken.java
- src/SaiyanKunt/chickenKiller/LootState.java
- src/SaiyanKunt/chickenKiller/PickupLoot.java
- src/SaiyanKunt/chickenKiller/Task.java
https://www.powerbot.org/community/topic/1330081-sw-application-osrs-chicken-killerlooterbone-burier/
3 functions, each can be turned on and off:
- Kill Chickens
- Pickup Feathers 
- Pickup and Bury Bones
> Chicken Killer/Looter/Bone Burier

- src/org/powerbot/script/rt6/Component.java
- src/org/powerbot/script/rt6/Constants.java
- src/org/powerbot/script/rt6/Hud.java
Fixes broken backpack and broken bank.
Addresses #1580
> Temporary workaround for broken widgets

- src/org/powerbot/bot/rt4/RandomEvents.java
- src/org/powerbot/script/rt4/Constants.java
> Cancel current action before interacting with random event

- src/org/powerbot/script/rt4/CacheItemConfig.java
A new opcode 42 was added recently.
> RT4 CacheItemConfig new opcode

- src/org/powerbot/script/rt6/CacheVarbitConfig.java
- src/org/powerbot/script/rt6/Npc.java
Added varbit cache reading and npc staging as was requested here https://github.com/powerbot/powerbot/issues/1136
> Added rt6 varbit cache reading and npc staging

- src/org/powerbot/script/rt6/ClientContext.java
- src/org/powerbot/script/rt6/ProductionInterface.java
Added utilities for interacting with Production Interface: http://runescape.wikia.com/wiki/Make-X
> Added Production Interface utilities

- src/org/powerbot/script/rt6/CacheVarbitConfig.java
- src/org/powerbot/script/rt6/Npc.java
Fixed IndexOutOfBounds exception and added config caching
> Added rt6 varbit cache reading and npc staging - patched

- src/main/java/org/powerbot/script/rt4/Combat.java
- src/main/java/org/powerbot/script/rt4/Constants.java
Couple of optimizations and additions, added component caching where possible.
https://github.com/powerbot/powerbot/pull/1527 can be closed.
> Combat upgrade - RT4

- src/main/java/org/powerbot/script/rt4/Widget.java
RT4 Widget now implements Iterable interface.
> Matched functionality of rt4 and rt6 widgets

- src/IntenseChanging/DragonBitterBuyer.java
- src/IntenseChanging/scripts/DragonBitterBuyer/DragonBitterBuyer.java
Let me know if there's anything else I need to do.
> Initial add of script.

- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Prayer.java
Prayers widget changed from 271 to 541, added Rigour, Augury, and Preserve effects.
> Added missing rt4 prayers and fixed the widget

- src/main/java/org/powerbot/script/rt6/Component.java
A potential fix addressing #1544. Raising the recursion depth seems to fix the issue for most, if not all, components.
> Potential components fix

- src/main/java/org/powerbot/script/rt4/Game.java
Contains a check if ESC can be used for interface closing.
> Added rt4 keybind support

- src/Spearless/WcFishMine.java
Publishing a Woodcutting,Mining and Fishing script
> WcFishMine script

- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Widgets.java
- src/main/java/org/powerbot/script/rt6/Constants.java
- src/main/java/org/powerbot/script/rt6/Widgets.java
Implemented for both the rt4 and rt6.
> Added universal interface closing methods

- src/main/java/org/powerbot/script/rt6/CacheComponentConfig.java
- src/main/java/org/powerbot/script/rt6/Component.java
As requested in https://github.com/powerbot/powerbot/issues/971. Component#tooltip() already existed so I added a method named componentTooltips() to avoid confusion.
> Added rt6 component tooltip support

- src/Spearless/WcFishMine.java
Fixed some code and functional script issues
Adding some paintings
>  WcFishMine.java

- src/Tyskie/src/scripts/TSuperHeat/TSuperHeat.java
- src/Tyskie/src/scripts/TSuperHeat/resources/Antiban.java
- src/Tyskie/src/scripts/TSuperHeat/resources/MyConstants.java
- src/Tyskie/src/scripts/TSuperHeat/resources/Task.java
- src/Tyskie/src/scripts/TSuperHeat/tasks/Bank.java
- src/Tyskie/src/scripts/TSuperHeat/tasks/Superheat.java
For more information check out this topic: https://www.powerbot.org/community/topic/1334360-free-osrs-f2pp2p-magicsmithing-tyskies-tsuperheat/
> Added Tyskie's TSuperHeat

- src/powerkyle628/scripts/LogIncinerator.java
- removed obfuscated class reference, which would make compilation fail on next client release
- fixed the manifest topic ID; valid topic IDs are required for a script to be listed on the SDN.
@kyle628
> Fix powerkyle628s script

- src/Vaynex/Antiban.java
- src/Vaynex/BarbLootnCook.java
- src/Vaynex/Task.java
- src/Vaynex/tasks/Cook.java
- src/Vaynex/tasks/Drop.java
- src/Vaynex/tasks/Loot.java
> Initial script upload 

- src/main/java/org/powerbot/script/rt6/Constants.java
- fixes `Component.bind()`
- fixes `Action.queued()`
> Fix component widgets

- src/Tyskie/scripts/TPowerChop/TPowerChop.java
- src/Tyskie/scripts/TPowerChop/resources/Antiban.java
- src/Tyskie/scripts/TPowerChop/resources/MyConstants.java
- src/Tyskie/scripts/TPowerChop/resources/Task.java
- src/Tyskie/scripts/TPowerChop/tasks/Chop.java
- src/Tyskie/scripts/TPowerChop/tasks/Drop.java
For more information check out this topic: https://www.powerbot.org/community/topic/1334458-free-osrs-f2p-woodcutting-tyskies-tpowerchop/
> Added Tyskie's TPowerChop

- src/baikai00/scripts/DHChecker.java
- src/baikai00/scripts/Fire.java
- src/baikai00/scripts/ReadIni.java
- src/baikai00/scripts/Utils.java
- src/baikai00/scripts/Walker.java
> AutoFireCraft

- src/baikai00/scripts/Utils.java
> fixed issue with using non-final variable in anonymous inner class

- src/PhDinStupidity/chocduster/DConstants.java
- src/PhDinStupidity/chocduster/Duster.java
- src/PhDinStupidity/chocduster/interfaces/Task.java
- src/PhDinStupidity/chocduster/tasks/BankChocolate.java
- src/PhDinStupidity/chocduster/tasks/KnifeDustChocolate.java
Adding my chocolate dusting script for OSRS.
> Initial Commit for PhD in Stupidity

- src/noobienoobie123/FaladorCowKiller/FaladorCowKiller.java
- src/noobienoobie123/FaladorCowKiller/tasks/Bank.java
- src/noobienoobie123/FaladorCowKiller/tasks/CowKiller.java
- src/noobienoobie123/FaladorCowKiller/tasks/Looter.java
- src/noobienoobie123/FaladorCowKiller/tasks/WalkToCowPenFalador.java
fixed stuck on gate and fixed paint counter for cowHides
> 2nd Commit

- src/noobienoobie123/FaladorCowKiller/FaladorCowKiller.java
- src/noobienoobie123/FaladorCowKiller/tasks/Bank.java
- src/noobienoobie123/FaladorCowKiller/tasks/Looter.java
- src/noobienoobie123/FaladorCowKiller/tasks/WalkToCowPenFalador.java
- src/noobienoobie123/FaladorCowKiller/tasks/WalkToCowPenLumbridge.java
Added Lumbridge support for cows. How do I republish this on the SDN?
> Added Lumbridge Support

- src/noobienoobie123/FaladorCowKiller/FaladorCowKiller.java
- src/noobienoobie123/FaladorCowKiller/tasks/BankForTan.java
- src/noobienoobie123/FaladorCowKiller/tasks/Tan.java
- src/noobienoobie123/FaladorCowKiller/tasks/WalkToTanner.java
Added Tanning Support in Alkarid
> Added Tanning Support

- src/baikai00/scripts/Utils.java
script stopped change to script suspend when the condition start starts.
add status when script suspend.
> add status when script suspend

- src/needscroll/BanannaGrabber/BanannaGrabber.java
- src/needscroll/BanannaGrabber/Task.java
- src/needscroll/BanannaGrabber/Tasks/Antiban.java
- src/needscroll/BanannaGrabber/Tasks/CastleWarsBank.java
- src/needscroll/BanannaGrabber/Tasks/EdgevilleBank.java
- src/needscroll/BanannaGrabber/Tasks/Fill.java
- src/needscroll/BanannaGrabber/Tasks/Gather.java
- src/needscroll/BanannaGrabber/Tasks/GeBank.java
Thread here
https://www.powerbot.org/community/topic/1335857-sw-applicationdelay-for-2-daysno-reqs500khbanana-apple-and-grape-gathering-bot/
> Adding bananna grabber

- src/needscroll/GrapeGrabber/GrapeGrabber.java
- src/needscroll/GrapeGrabber/Task.java
- src/needscroll/GrapeGrabber/Tasks/Antiban.java
- src/needscroll/GrapeGrabber/Tasks/Banking.java
- src/needscroll/GrapeGrabber/Tasks/GetSecondFloor.java
- src/needscroll/GrapeGrabber/Tasks/GetThirdFloor.java
- src/needscroll/GrapeGrabber/Tasks/GoSecond.java
- src/needscroll/GrapeGrabber/Tasks/Waiter.java
Thread here.
https://www.powerbot.org/community/topic/1335857-sw-applicationdelay-for-2-daysno-reqs500khbanana-apple-and-grape-gathering-bot/
> Adding GrapeGrabber

- src/needscroll/LimpwurtGrabber/LimpwurtGrabber.java
- src/needscroll/LimpwurtGrabber/Task.java
- src/needscroll/LimpwurtGrabber/Tasks/Antiban.java
- src/needscroll/LimpwurtGrabber/Tasks/Banking.java
- src/needscroll/LimpwurtGrabber/Tasks/Gather.java
- src/needscroll/LimpwurtGrabber/Tasks/GoDungeon.java
- src/needscroll/LimpwurtGrabber/Tasks/Ladder.java
- src/needscroll/LimpwurtGrabber/Tasks/Teleport.java
- src/needscroll/LimpwurtGrabber/Tasks/WalkHills.java
Thread here
https://www.powerbot.org/community/topic/1336613-600khrs3-limpwurtroot-grabber/
> Adding Limpwurtroot Grabber

- src/Spearless/SYewChopper.java
User imported obfuscated classes, causing the script to not compile.
@TendingInfinite
> Fix SYewChopper

- src/hauntbrave/Curse/Curse.java
- src/hauntbrave/HigherAlch/HigherAlch.java
- src/hauntbrave/ZamWine/utils/WelcomeWindow.java
Two fixes: 
1. Fixes the package declarations;
2. Removed String switches, since they are incompatible with Java 6. 
@everettyang
> Fix hauntbrave package

- src/main/java/org/powerbot/bot/rt4/RandomEvents.java
33 -> 34
33 is now 'Enter amount'
> Update chat widget so typing works

- src/sscripts/sgaltar/SGAltar.java
- src/sscripts/sgaltar/gui/Gui.java
- src/sscripts/sgaltar/tasks/Altar.java
- src/sscripts/sgaltar/tasks/Bank.java
- src/sscripts/sgaltar/tasks/Banking.java
- src/sscripts/sgaltar/tasks/CloseBank.java
- src/sscripts/sgaltar/tasks/EnterPortal.java
- src/sscripts/sgaltar/tasks/LeaveHouse.java
- src/sscripts/sgaltar/tasks/PortalChat.java
- src/sscripts/sgaltar/tasks/walk/WalkToPortal.java
- src/sscripts/sgaltar/tasks/walk/Walker.java
- src/sscripts/sgaltar/tasks/walk/Walking.java
fixed some compiling issues and added some helpfull stuff.
> added failsave and auto stop

- src/Dark/scripts/ranged_guild/EscapeThread.java
- src/Dark/scripts/ranged_guild/RangeMain.java
Added ranging guild script for OSRS
> Initial Commit - Ranging Guild

- src/m0tionl3ss/CharterBuyer/scripts/CharterBuyer.java
- src/m0tionl3ss/CharterBuyer/tasks/BuyFromCharterShop.java
- src/m0tionl3ss/CharterBuyer/tasks/Quit.java
- src/m0tionl3ss/CharterBuyer/tasks/RunToCharterMember.java
- src/m0tionl3ss/JewelEnchanter/scripts/JewelEnchanter.java
- src/m0tionl3ss/JewelEnchanter/tasks/Bank.java
- src/m0tionl3ss/JewelEnchanter/tasks/EnchantJewelery.java
- src/m0tionl3ss/JewelEnchanter/util/Tools.java
> renamed main classes, cleaned some imports

- src/m0tionl3ss/SandRunner/scripts/SandRunner.java
> Fixed SandRunner attribute

- src/iDzn/OldschoolRS/NoobNester/NoobNester.java
- src/iDzn/OldschoolRS/OgreCannon/OgreCannon.java
- src/iDzn/OldschoolRS/OgreCannon/Task.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/Telek.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/deployCannon.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/fireCannon.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/leaveRails.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/lootSeeds.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/railSqueeze.java
- src/iDzn/OldschoolRS/OgreCannon/Tasks/repairCannon.java
- src/iDzn/OldschoolRS/Task.java
- src/iDzn/OldschoolRS/Tasks/Bank.java
- src/iDzn/OldschoolRS/Tasks/Drop.java
- src/iDzn/OldschoolRS/Tasks/Mine.java
- src/iDzn/OldschoolRS/Tasks/OpenNests.java
- src/iDzn/OldschoolRS/Tasks/OpenRings.java
- src/iDzn/OldschoolRS/Tasks/Walk.java
- src/iDzn/OldschoolRS/Tasks/Withdraw.java
- src/iDzn/OldschoolRS/Tasks/WithdrawRings.java
- src/iDzn/OldschoolRS/Walker.java
> Scripts Upload

- src/sheel/BarbarianFisherAndCooker/BarbarianFisherAndCooker.java
- src/sheel/BarbarianFisherAndCooker/Constants.java
- src/sheel/BarbarianFisherAndCooker/TreeBot/BranchTask.java
- src/sheel/BarbarianFisherAndCooker/TreeBot/LeafTask.java
- src/sheel/BarbarianFisherAndCooker/TreeBot/TreeBot.java
- src/sheel/BarbarianFisherAndCooker/TreeBot/TreeTask.java
- src/sheel/BarbarianFisherAndCooker/branches/ContainsFeathers.java
- src/sheel/BarbarianFisherAndCooker/branches/ContainsRawFood.java
- src/sheel/BarbarianFisherAndCooker/branches/InBankRegion.java
- src/sheel/BarbarianFisherAndCooker/branches/InCookingRegion.java
- src/sheel/BarbarianFisherAndCooker/branches/InFishingRegion.java
- src/sheel/BarbarianFisherAndCooker/branches/InLodestoneRegion.java
- src/sheel/BarbarianFisherAndCooker/branches/IsBankOpen.java
- src/sheel/BarbarianFisherAndCooker/branches/IsCooking.java
- src/sheel/BarbarianFisherAndCooker/branches/IsCookingInterfaceOpen.java
- src/sheel/BarbarianFisherAndCooker/branches/IsFishing.java
- src/sheel/BarbarianFisherAndCooker/branches/IsInventoryFull.java
- src/sheel/BarbarianFisherAndCooker/leaves/Cook.java
- src/sheel/BarbarianFisherAndCooker/leaves/Fish.java
- src/sheel/BarbarianFisherAndCooker/leaves/LoadBankPreset.java
- src/sheel/BarbarianFisherAndCooker/leaves/OpenBank.java
- src/sheel/BarbarianFisherAndCooker/leaves/StopBot.java
- src/sheel/BarbarianFisherAndCooker/leaves/UseFire.java
- src/sheel/BarbarianFisherAndCooker/leaves/WaitUntilNotCooking.java
- src/sheel/BarbarianFisherAndCooker/leaves/WaitUntilNotFishing.java
- src/sheel/BarbarianFisherAndCooker/leaves/WalkToBank.java
- src/sheel/BarbarianFisherAndCooker/leaves/WalkToCookingRegion.java
- src/sheel/BarbarianFisherAndCooker/leaves/WalkToFishingRegion.java
This is my first script and would like to add it to the open script repository. This uses TreeBot, a tree-like bot flow (for tree based task creation) that I have made a basic implementation of based on other bot APIs I've used. Re-opening this pull request after fixing bugs and adding a UI.
> Add RS3 BarbarianFisherAndCooker script

- sheel/RS3TreeBot/BranchTask.java
- sheel/RS3TreeBot/LeafTask.java
- sheel/RS3TreeBot/TreeBot.java
- sheel/RS3TreeBot/TreeTask.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/BarbarianFisherAndCooker.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/Constants.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/ContainsFeathers.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/ContainsRawFood.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/InBankRegion.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/InCookingRegion.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/InFishingRegion.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/InLodestoneRegion.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/IsBankOpen.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/IsCooking.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/IsCookingInterfaceOpen.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/IsFishing.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/branches/IsInventoryFull.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/Cook.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/Fish.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/LoadBankPreset.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/OpenBank.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/StopBot.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/UseFire.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/WaitUntilNotCooking.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/WaitUntilNotFishing.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/WalkToBank.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/WalkToCookingRegion.java
- sheel/scripts/RS3/BarbarianFisherAndCooker/leaves/WalkToFishingRegion.java
Fixing directory structure so new scripts can be added. Package structure also fixed so code will compile on SDN
> Fix directory structure and packages

- src/main/java/org/powerbot/script/rt6/Constants.java
Bank won't close due to widget change. Verified other widgets.
> Fix banking rs3

- src/iDzn/KegBalancer/KegBalancer.java
- src/iDzn/KegBalancer/Task.java
- src/iDzn/KegBalancer/Tasks/Anti.java
- src/iDzn/KegBalancer/Tasks/Bank.java
- src/iDzn/KegBalancer/Tasks/Eat.java
- src/iDzn/KegBalancer/Tasks/Energy.java
- src/iDzn/KegBalancer/Tasks/KegMe.java
- src/iDzn/KegBalancer/Tasks/Walk.java
- src/iDzn/KegBalancer/Tasks/WithdrawCake.java
- src/iDzn/KegBalancer/Tasks/WithdrawLobster.java
- src/iDzn/KegBalancer/Tasks/WithdrawMonk.java
- src/iDzn/KegBalancer/Tasks/WithdrawShark.java
- src/iDzn/KegBalancer/Tasks/WithdrawSword.java
- src/iDzn/KegBalancer/Tasks/WithdrawTuna.java
- src/iDzn/KegBalancer/Walker.java
> KegBalancer Script Upload

- src/iDzn/KegBalancer/KegBalancer.java
- src/iDzn/KegBalancer/Tasks/KegMe.java
Removed an old println I used to check for an error, no longer needed in there as will now return every time execute is carried out.
Also this scripts hasn't been showing in the SDN for people to use; wasn't sure if that's something I've done?
> Removing println

- src/iDzn/OgreCannon/OgreCannon.java
- src/iDzn/OgreCannon/Tasks/Telek.java
Fixing the spamming issue with tele grab, also added a failsafe and made the loot counter more efficient.
> Fixing spam issue

- src/iDzn/KegBalancer/KegBalancer.java
- src/iDzn/KegBalancer/Tasks/Anti.java
- src/iDzn/KegBalancer/Tasks/Walk.java
- src/iDzn/KegBalancer/Tasks/Withdraw.java
Trying to fix a bug by changing the final tile in which the walking class stop at.
> Updating final bank tile

- src/stumpy3toes/scripts/stumpyisland/tasks/Chat.java
- src/stumpy3toes/scripts/stumpyisland/tasks/FinancialAdvisor.java
- src/stumpy3toes/scripts/stumpyisland/tasks/RoofSetting.java
- src/stumpy3toes/scripts/stumpyisland/tasks/SurvivalExpert.java
- src/superchaoran/HerbsUlitimate/jobs/Bank.java
This script hasn't been updated for a long time and the creator hasn't logged in either.
> Bug free tutorial island

- src/iDzn/ConstructUp/ConstructUp.java
- src/iDzn/ConstructUp/Task.java
- src/iDzn/ConstructUp/Tasks/Butler.java
- src/iDzn/ConstructUp/Tasks/CCWidgets.java
- src/iDzn/ConstructUp/Tasks/Dungeon.java
- src/iDzn/ConstructUp/Tasks/FailSafe.java
- src/iDzn/ConstructUp/Tasks/HouseNavigation.java
- src/iDzn/ConstructUp/Tasks/Phials.java
New construction script added.
> Fresh upload

- src/iDzn/ConstructUp/ConstructUp.java
- src/iDzn/ConstructUp/Tasks/Butler.java
- src/iDzn/ConstructUp/Tasks/CCWidgets.java
- src/iDzn/ConstructUp/Tasks/Dungeon.java
- src/iDzn/ConstructUp/Tasks/FailSafe.java
- src/iDzn/ConstructUp/Tasks/HouseNavigation.java
- src/iDzn/ConstructUp/Tasks/Phials.java
Added some fixes for resizable mode to use widgets and not co-ords. Also moved a level up widget handler into main class rather than just in the butler class as those not using a butler would of been stuck.
> Uploading fixes to ConstructUp Script

- src/iDzn/ConstructUp/ConstructUp.java
- src/iDzn/ConstructUp/Tasks/Butler.java
- src/iDzn/ConstructUp/Tasks/CCWidgets.java
- src/iDzn/ConstructUp/Tasks/Phials.java
I've tidied up a lot of the repeated widgets as advised due to simplifying maintenance. Also added a resizable paint for those who don't play in fixed screen mode.
> Widget tidy & Resizable Paint

- src/main/java/org/powerbot/script/rt4/Inventory.java
Reduces inventory drop time by over 15 seconds
> A drop method with shift click ability

- src/DieselSkrt/DRuneRunner/DRuneRunner.java
- src/DieselSkrt/DRuneRunner/Task.java
- src/DieselSkrt/DRuneRunner/Trade.java
- src/DieselSkrt/DRuneRunner/Walker.java
- src/DieselSkrt/DRuneRunner/tasks/Bank.java
- src/DieselSkrt/DRuneRunner/tasks/EnterPortal.java
- src/DieselSkrt/DRuneRunner/tasks/EnterRuins.java
- src/DieselSkrt/DRuneRunner/tasks/GoToAltar.java
- src/DieselSkrt/DRuneRunner/tasks/GoToBank.java
- src/DieselSkrt/DRuneRunner/tasks/TradeCrafter.java
Initial commit of DRuneRunner script.
> init commit

- src/main/java/org/powerbot/script/rt6/Camera.java
- src/main/java/org/powerbot/script/rt6/Game.java
Adds support for using the WASD keys instead of the directional keys to change the angle and pitch of the camera.
> WASD Camera Turning

- src/Aff1x/choppenheimer/Choppenheimer.java
- src/Aff1x/choppenheimer/Task.java
- src/Aff1x/choppenheimer/Tasks/Bank.java
- src/Aff1x/choppenheimer/Tasks/Chop.java
- src/Aff1x/choppenheimer/Tasks/Task.java
- src/Aff1x/choppenheimer/Tasks/Walk.java
- src/Aff1x/choppenheimer/Util/Config.java
- src/Aff1x/choppenheimer/Util/GUI.java
- src/Aff1x/choppenheimer/Util/TreeEnum.java
Features :
- Task Based
- Chops different trees
- ENUM Based so easily extendable
- Banking
- Single Banking class
- Walking to different spots
- Single Walking Task to walk to Trees and Bank
- repaint
- Simple GUI to select your tree!
> Choppenheimer

- src/main/java/org/powerbot/script/rt4/Worlds.java
1. Changes the parent class of `Worlds` from `IdQuery` to `AbstractQuery` and adds `IdentifiableQuery` as an implemented interface;
2. Formats the code;
> Fix Worlds

- src/main/java/org/powerbot/script/rt4/Game.java
checked and remains the same for resizable and fixed
> Fix magic tab (new icon ingame)

- src/main/java/org/powerbot/script/rt4/Game.java
> new spellbooks

- src/lilmj12/main/STCannons.java
- src/lilmj12/main/Task.java
- src/lilmj12/misc/Timer.java
- src/lilmj12/misc/Walker.java
- src/lilmj12/tasks/Bank.java
- src/lilmj12/tasks/Smelt.java
- src/lilmj12/tasks/Walk.java
> Added STCannons

- src/slicedtoast/KebabBuyer/Bank.java
@gabino75
Your script did not compile.
> Fixed Kebab Buyer

- src/main/java/org/powerbot/script/rt6/Camera.java
Added two methods to turn using default deviation and wasd keys
> Add More Turning

- src/main/java/org/powerbot/script/rt4/Constants.java
fixes world to screen issues from latest update
> viewport widget change for fixed mode

- src/swamlol/sheep/Sheep.java
fixed the directory and re-uploaded.
> uploading script(fixed dir)

- src/main/java/org/powerbot/script/rt4/Constants.java
pls merge before the other PR is merged in the RSBot project
> To fix lobby login

- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Game.java
matches RT6 (in game class)
added some constants also
> Added logout method to RT4

- src/main/java/org/powerbot/script/PollingScript.java
- src/main/java/org/powerbot/script/rt4/ClientContext.java
- src/main/java/org/powerbot/script/rt6/ClientContext.java
Upon merge script writers will have a minimum of 2 weeks to adapt their scripts (override canBreak()) - though not required (not a breaking change).
https://github.com/powerbot/powerbot/issues/1412
> Initial phase of Kill Timer

- src/main/java/org/powerbot/script/rt4/Constants.java
This resolves the bank depositing problems.
> Updates CHAT_INPUT_TEXT

- src/main/java/org/powerbot/script/rt6/Constants.java
added in the other bank preset widgets but no functionality yet
couldn't verify chat widgets are correct as my PC can barely run rs3
https://github.com/powerbot/powerbot/issues/1870
> update rt6 widgets

- src/drusepth/scripts/ClaySofteningState.java
- src/drusepth/scripts/EdgevilleClaySoftener.java
- src/drusepth/scripts/tasks/DepositItemsTask.java
- src/drusepth/scripts/tasks/SeekObjectTask.java
- src/drusepth/scripts/tasks/Task.java
- src/drusepth/scripts/tasks/WithdrawItemsTask.java
[Forums thread here](https://www.powerbot.org/community/topic/1344654-osrs-edgeville-clay-softener/).
* Withdraws 14 buckets and 14 clay from the bank
* Runs to the nearest well and softens all clay in inventory
* Returns to the bank and deposits all soft clay
* Runs until you've deposited the last of your clay in your bank as soft clay
* Perfect looping (starts over while keeping the bank tab open and reuses it)
> [OSRS] Edgeville clay softener script

- src/sscripts/sgaltar/SGAltar.java
- src/sscripts/sgaltar/data/Data.java
- src/sscripts/sgaltar/gui/Gui.java
- src/sscripts/sgaltar/tasks/Altar.java
- src/sscripts/sgaltar/tasks/Antiban.java
- src/sscripts/sgaltar/tasks/Banking.java
- src/sscripts/sgaltar/tasks/CloseBank.java
- src/sscripts/sgaltar/tasks/EnterPortal.java
- src/sscripts/sgaltar/tasks/LeaveHouse.java
- src/sscripts/sgaltar/tasks/PortalChat.java
- src/sscripts/sgaltar/tasks/rimmington/Phials.java
- src/sscripts/sgaltar/tasks/rimmington/ToPortal.java
- src/sscripts/sgaltar/tasks/walk/WalkEnergy.java
- src/sscripts/sgaltar/tasks/walk/WalkToPortal.java
- src/sscripts/sgaltar/tasks/walk/Walking.java
now supports: rimmington, antipattern, better gui, bounds
> V2.03 - bugfixes, new features

- src/sscripts/sgaltar/SGAltar.java
- src/sscripts/sgaltar/tasks/Altar.java
- src/sscripts/sgaltar/tasks/Antiban.java
- src/sscripts/sgaltar/tasks/EnterPortal.java
- src/sscripts/sgaltar/tasks/LeaveHouse.java
- src/sscripts/sgaltar/tasks/PortalChat.java
- src/sscripts/sgaltar/tasks/rimmington/Phials.java
- src/sscripts/sgaltar/tasks/rimmington/ToPortal.java
bugfix (widget changed), added some overall inprovements
> widget changed, better performance

- src/Elt/AlKharidFishNCook/tasks/Cook.java
added a condition to help prevent eating fish while cooking
> added a condition

- src/PanconMortadela/scripts/Canifi/Canifi.java
- src/PanconMortadela/scripts/Canifi/Canifi2.java
- src/PanconMortadela/scripts/Utilitys/Areas.java
> Scripts Canifi Agi

- src/main/java/org/powerbot/script/rt4/Magic.java
#1885 
Don't have an account to test but logic seems correct. 
Random spaces come from auto formatting.
> Support for redirected teleports

- src/main/java/org/powerbot/script/rt4/Npc.java
> added getters for npc colors

- src/main/java/org/powerbot/script/rt6/Constants.java
> update inventory (verified bank and deposit box hasn't changed)

- src/main/java/org/powerbot/script/rt4/Menu.java
#1903  
potentially also https://github.com/powerbot/powerbot/issues/1032
> fix sporadic menu

- src/GANerated_Bots/chickenKiller/ChickenKiller.java
Really simple chicken killer, test to make sure I am able to pr and use the open script repository
> Gan chickenkiller

- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Constants.java
> Fix banking & add quantity functionality

- src/main/java/org/powerbot/script/rt4/Chat.java
fixes https://github.com/powerbot/powerbot/issues/1949
> update chat index

- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Inventory.java
Adds the methods withdrawModeQuantity( for getting the Amount that is selected for withdraw mode) and quantityComponentValue ( for getting the component value of a quantity ) to Bank and adds Constants for them.
Adds the method isFull() to Inventory, updates the Constants for this changes and makes use of the Constant in Inventory.
> Adds methods to Bank and Inventory.

- src/main/java/org/powerbot/script/rt4/DepositBox.java
Adds methods to deposit box that are present in Bank.
> Adds methods to deposit box

- src/main/java/org/powerbot/script/Actionable.java
- src/main/java/org/powerbot/script/Nameable.java
- src/main/java/org/powerbot/script/rt4/BasicQuery.java
- src/main/java/org/powerbot/script/rt4/ItemQuery.java
- src/main/java/org/powerbot/script/rt4/PlayerQuery.java
- src/main/java/org/powerbot/script/rt6/GroundItemQuery.java
- src/main/java/org/powerbot/script/rt6/ItemQuery.java
- src/main/java/org/powerbot/script/rt6/MobileIdNameQuery.java
- src/main/java/org/powerbot/script/rt6/PlayerQuery.java
Address #1953 
Adds support for filtering by Action and by Name using a `Collection<String>`
> Adds support for Collections in Actionable and Nameable queries

- src/main/java/org/powerbot/script/Input.java
I'm not sure if this is the best way to do this, however I wanted the ability to cancel out of anything by interrupting the thread and this seemed most effective.
Solves #1910
> Adding Thread#interrupted check to apply

- src/main/java/org/powerbot/script/rt4/Constants.java
> Fix auto-login

- src/main/java/org/powerbot/script/rt6/Game.java
Update "Exit to Lobby" and "Logout" component IDs.
> Update "Exit to Lobby" and "Logout" component IDs.

- src/main/java/org/powerbot/script/rt6/Constants.java
- src/main/java/org/powerbot/script/rt6/Game.java
Is not a child of the map any longer
https://github.com/powerbot/powerbot/issues/1979
> fix map blocking (compass)

- src/main/java/org/powerbot/bot/rt4/client/BarComponent.java
- src/main/java/org/powerbot/bot/rt4/client/CombatStatus.java
- src/main/java/org/powerbot/script/rt4/Actor.java
tested on zulrah in fixed and resizable
_**waiting for confirmation that it's pushed to live updater before release**_
> Added hook for width of bar for true health eval

- src/main/java/org/powerbot/script/rt4/Projectile.java
https://github.com/powerbot/powerbot/issues/1988
> Update Projectiles (rt4) to account for non-npc targets

- src/main/java/org/powerbot/script/rt6/Bank.java
The shortcut for sets 3 and onwards is not just a simple number press.
> Update `Bank#presetGear` to only use shortcut for first two sets.

- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Inventory.java
- src/main/java/org/powerbot/script/rt4/Item.java
#1956 caused some breakages. This fixes them.
> Fix breakages caused by PR

- src/Elt/AlKharidFishNCook/tasks/Cook.java
Now clicks the range then selects the first fish to cook in the UI
> Updated for cooking UI

- src/Elt/AlKharidFishNCook/tasks/Fish.java
changed some sleep timers to seem less bot like
> changed some sleep timers

- src/main/java/org/powerbot/script/rt4/Interactive.java
- src/main/java/org/powerbot/script/rt6/Interactive.java
Leading on from the conversation in https://github.com/powerbot/powerbot/pull/2021, I'm requesting getters and setters for the `boundingModel` on `Interactive` on rt4 and rt6.
> Implement getters and setters for Interactive bounding boxes

- src/main/java/org/powerbot/script/rt4/CacheItemConfig.java
- src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
- src/main/java/org/powerbot/script/rt4/CacheObjectConfig.java
- src/main/java/org/powerbot/script/rt6/CacheNpcConfig.java
- src/main/java/org/powerbot/script/rt6/CacheObjectConfig.java
- src/main/java/org/powerbot/script/rt6/CacheVarbitConfig.java
Requires CacheWorker to be made public to work, issue here https://github.com/powerbot/powerbot/issues/2048
> Make CacheConfigs#load public

- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Inventory.java
This will fix indexCenterPoint and methods that depend on it, such as drag.
> Fixes indexCenterPoint

- src/main/java/org/powerbot/script/rt4/Inventory.java
Fixes reference mistakes made in #2052 .
> Fixes reference breakage

- src/main/java/org/powerbot/script/rt4/Combat.java
Use special attack orb as backup for special attack
> Refactor rt4 Combat to use component query

- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Constants.java
> Add an unreachable bank

- src/PaulChew1988/PMiner/CombatTasks/AttackChicken.java
- src/PaulChew1988/PMiner/CombatTasks/SelectStyles.java
- src/PaulChew1988/PMiner/GrandExchange.java
- src/PaulChew1988/PMiner/Main.java
- src/PaulChew1988/PMiner/PMinerConst.java
- src/PaulChew1988/PMiner/Task.java
- src/PaulChew1988/PMiner/Tasks/AutoPick.java
- src/PaulChew1988/PMiner/Tasks/Banking.java
- src/PaulChew1988/PMiner/Tasks/Drop.java
- src/PaulChew1988/PMiner/Tasks/Mine.java
- src/PaulChew1988/PMiner/Tasks/Sell.java
- src/PaulChew1988/PMiner/Tasks/SubTasks/GeToBank.java
- src/PaulChew1988/PMiner/Tasks/Walk.java
- src/PaulChew1988/PMiner/Walker.java
[PaulChew1988.zip](https://github.com/powerbot/powerbot/files/3342430/PaulChew1988.zip)
added PMining script
> Added Pminer

- src/main/java/org/powerbot/script/rt4/Item.java
Patches centerPoint and boundingRect with offsets to match the latest update.
> Temporarily patches centerPoint and boundingRect

- src/main/java/org/powerbot/script/rt4/World.java
https://i.imgur.com/dhqtYKD.png
> Swap deadman and PVP texture

- src/main/java/org/powerbot/bot/rt4/HashTable.java
- src/main/java/org/powerbot/bot/rt4/client/IterableHashTable.java
- src/main/java/org/powerbot/bot/rt4/client/Node.java
- src/main/java/org/powerbot/script/rt4/Component.java
- src/main/java/org/powerbot/script/rt4/Constants.java
Fixes component calculations.
Fixes #2083
> Components fix

- src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
> Fix for NPC buffer underflow exception.

- src/main/java/org/powerbot/bot/cache/JagexStream.java
- src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
Reverts powerbot/RSBot-API#2104
> Revert "temporary workaround for deformed cache NPCs"

- src/main/java/org/powerbot/script/Input.java
Adds a method for checking if the client has focus. Resolves #2111
> added isFocused method

- src/main/java/org/powerbot/script/rt4/Worlds.java
untested but logic seems sound, right?
> Don't try to open world changer if already open

- src/main/java/org/powerbot/script/rt4/Constants.java
> Fixed disconnected login state

- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Constants.java
Fixes #2130 
May be related to #2092
> Fixed withdraw quantity

- src/main/java/org/powerbot/script/rt4/Constants.java
- src/main/java/org/powerbot/script/rt4/Game.java
Adds support for logging out from the world switch screen. Fixes #2129
> Fixed game logout on world switch screen

- src/main/java/org/powerbot/script/rt4/Player.java
> Use health from Combat class if is local player

- src/main/java/org/powerbot/script/rt4/Bank.java
> Added overloads for specifying wait-for condition on withdrawing

- src/main/java/org/powerbot/script/rt4/LocalPath.java
- src/main/java/org/powerbot/script/rt4/Movement.java
- src/main/java/org/powerbot/script/rt4/Path.java
BFS will be used instead of Dijkstra's, the graph structure will be
lazily initialized, and unneeded costly calls are removed. The changes 
reduce computation times by roughly x150.
> Re-implement underlying logic for LocalPath

- src/main/java/org/powerbot/script/rt4/Actor.java
- src/main/java/org/powerbot/script/rt4/BoundingModel.java
- src/main/java/org/powerbot/script/rt4/GameObject.java
- src/main/java/org/powerbot/script/rt4/Model.java
- src/main/java/org/powerbot/script/rt4/Npc.java
Reverts powerbot/RSBot-API#2160
> Revert "Allow npc and object interactions to rely on cache models"

- src/main/java/org/powerbot/script/rt4/Actor.java
- src/main/java/org/powerbot/script/rt4/BoundingModel.java
- src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
- src/main/java/org/powerbot/script/rt4/GameObject.java
- src/main/java/org/powerbot/script/rt4/Interactive.java
- src/main/java/org/powerbot/script/rt4/Model.java
- src/main/java/org/powerbot/script/rt4/Npc.java
These changes resolve the model issues that have been raised.
**Fix valid cache models yielding invalid points edge case**
No longer assume points retrieved from valid cache models are correct;
only return if not (-1,-1) and otherwise use bounding model as fallback.
**Support scaling of NPC models**
Fits models that are reused across multiple npcs to size, for example,
cow and cow calves share the same model but have different interactable
bounds.
> Model interaction improvements

- .github/workflows/maven.yml
- pom.xml
- src/main/java/org/powerbot/bot/Reflector.java
- src/main/java/org/powerbot/script/AbstractScript.java
- src/main/java/org/powerbot/script/Area.java
- src/main/java/org/powerbot/script/Bot.java
- src/main/java/org/powerbot/script/ClientContext.java
- src/main/java/org/powerbot/script/SpeedException.java
- src/main/java/org/powerbot/script/rt4/Actor.java
- src/main/java/org/powerbot/script/rt4/CacheItemConfig.java
- src/main/java/org/powerbot/script/rt4/CacheObjectConfig.java
- src/main/java/org/powerbot/script/rt4/Game.java
- src/main/java/org/powerbot/script/rt4/LocalPath.java
- src/main/java/org/powerbot/script/rt4/TileMatrix.java
- src/main/java/org/powerbot/script/rt4/Widget.java
- src/main/java/org/powerbot/script/rt4/Widgets.java
- src/main/java/org/powerbot/util/ScriptBundle.java
- Moved to Java 11
- isAccessible -> canAccess
- Ran code inspection and fixed up some easy warnings
> Code cleanup & Java 11

- src/main/java/org/powerbot/bot/rt4/BankPin.java
- src/main/java/org/powerbot/bot/rt4/RandomEvents.java
- src/main/java/org/powerbot/bot/rt4/WidgetCloser.java
- src/main/java/org/powerbot/script/rt4/Bank.java
- src/main/java/org/powerbot/script/rt4/Camera.java
- src/main/java/org/powerbot/script/rt4/Combat.java
- src/main/java/org/powerbot/script/rt4/DepositBox.java
- src/main/java/org/powerbot/script/rt4/Game.java
- src/main/java/org/powerbot/script/rt4/Interactive.java
- src/main/java/org/powerbot/script/rt4/Menu.java
- src/main/java/org/powerbot/script/rt4/Movement.java
- src/main/java/org/powerbot/script/rt4/Prayer.java
- src/main/java/org/powerbot/script/rt4/TilePath.java
- src/main/java/org/powerbot/script/rt4/Widgets.java
- src/main/java/org/powerbot/script/rt4/World.java
- src/main/java/org/powerbot/script/rt4/Worlds.java
As the title suggests, this pull request replaces each anonymous class that extends `Condition.Check` with a corresponding lambda expression, and therefore reduces the amount of visual clutter in the code. 😊
> Replace anonymous classes with lambda expressions

- src/main/java/org/powerbot/script/rt4/Bank.java
Additionally, this also fixes/harmonises the accompanying Javadoc `@return` comments. 😊
> Add missing Javadoc @param comments for waitFor
