rt4/Bank.java
rt6/Bank.java

Add withdrawal of item instance so as to not reselect the query if you already have the item instance. Also, update documentation.

Add withdrawal of item instance

---

rt4/Player.java

There have been a few commits to this recently, but it was still broken.
Code to demonstrate that using a mask doesn't work #1178 (latest change isn't in client build yet)
```
int wrong = 0, correct = 0;
for (int i = 0; i < 13353; i++) {
if (((i + 512) & 0xfffffdff) != i) {
//System.out.println(i + " wrong returns " + ((i + 512) & 0xfffffdff));
wrong++;
} else {
correct++;
}
}
System.out.println("wrong: " + wrong + ", correct:" + correct);
```
It will currently only work in about half cases (not exactly since you can't wear all items)
`wrong: 6656, correct:6697`
If anyone wants to check this is a list of wearable items that I think will give the incorrect id with the current method https://gist.github.com/Logicail/1efbb5b2b74afe14bec2

Fix player appearance offset

---

src/helicopter12/scripts/Elder.java

Previous bug was double-indexing. Found through user testing.
Storing all respawn times preserves more information, to make the script smarter when doing antipattern.

Elder: Fix new randomization. Store respawn times for all trees

---

src/helicopter12/scripts/Elder.java

Object.nearest() seems to be flawed and may cause the script to crash when a player is running toward the object. Removed the object.nearest call and modified the select() call to pass a tile range of 10 to speed things up and serve the same purpose as the nearest call did.

Object detection update - Bug fix attempt

---

src/andyroo/blastfurnace/BlastFurnace.java

v 1.4c
fixed foreman payment when 60+
fixed a bug while collecting that should be handled by idle timer
added a check for coins subtracted to confirm payment
now checks exact amount of bars collected (assumed full load before)
urgent.

Blast Furnace v 1.4c: fixed foreman payment when 60+

---

rt6/Game.java

Added a failsafe for minimap component parsing if it fails by using ```contentType()```.

Minimap component failsafe

---

rt4/Bank.java

Withdraw all-but-one action was not correct and it caused the bot to only hover the item.

Fixed OSRS withdrawing all-but-one

---

rt4/Bank.java

Since bank tabs are now supported and use the same varp as noted withdrawing mode, the latter method had to be adjusted by adding a shift and a mask before checking the state.

Fixed a check if withdrawing noted is selected

---

src/org/powerbot/script/rt4/Constants.java
src/org/powerbot/script/rt4/Inventory.java
src/org/powerbot/script/rt4/Item.java

Fixes https://github.com/powerbot/powerbot/issues/1420. If no other inventory widgets are visible it always falls back to main inventory widget (149), because it's updated even if it's not visible. This means that inventory query can now be refreshed even if it's closed and it will load the latest data.
This pull request also contains improvements for two Item methods, valid() and stackSize(), which now do the same as their rt6 counterparts.

Updated Inventory components and improved Item#valid() and #stackSize()

---

src/org/powerbot/script/rt4/Actor.java

Since other methods for getting Actors health are deprecated and now use healthPercent() method, it should be made public.

Make rt4 Actor#healthPercent() public

---

src/org/powerbot/bot/rt4/RandomEvents.java

This fixes an issue where the bot would spam-click the "Dismiss" command until the npc disappeared.

Fixed random events dismiss spamming

---

src/org/powerbot/script/rt4/Constants.java

Previous tiles were offset for 8 squares to the east.

Added correct Draynor village unreachable banker tiles

---

src/org/powerbot/script/Textable.java

Instead of checking whether the desired text contains the entirety of the target, check whether the target contains the entirety of the desired text, [as suggested by Artificial](https://www.powerbot.org/community/topic/1321412-ctxchatselecttext-is-selecting-the-wrong-option/#comment-16179445).
Also, switched `toLowerCase()` to `toUpperCase()` because it's [faster](http://stackoverflow.com/a/29785961).

Switch contains condition; Uppercase text for efficiency

---

src/org/powerbot/bot/rt6/ExaminePattern.java

Due to [inefficient getViewport() calculations](https://github.com/powerbot/powerbot/issues/1478), this antipattern took ~40 seconds on average to execute for GameObjects. 
The method has been improved and it should now take no longer than 3-4 seconds to complete.

Optimized rt6 ExaminePattern for GameObjects

---

src/org/powerbot/script/rt4/Actor.java

Solves https://github.com/powerbot/powerbot/issues/1519
[CombatStatusData#getHealthRatio()](https://github.com/powerbot/powerbot/blob/rsbot-api/src/org/powerbot/bot/rt4/client/CombatStatusData.java#L14-L16) returns 30 when health bar is visible and actor has full hp. Tested with both Npcs and Players and it returns the correct value.

Fixed rt4 Actor#healthPercent()

---

src/org/powerbot/bot/rt4/BankPin.java

Commit [#45b993d2](https://github.com/powerbot/powerbot/commit/45b993d2ab3a279bfd3bafd2d3947987f8387288#diff-9e599026ec5c39b57897f67765b1f41bR45) implicitly was casting the character to an integer, so it was being converted to the wrong value.

Fix Bank Pins (issue #1549)

---

src/org/powerbot/script/rt4/Item.java

Fixes the mean in next point calculation. Center rectangle must be offset for 1/8 of the bounding one in order for its center point to be the actual item center point. Fixes https://github.com/powerbot/powerbot/issues/1592, @Moosheplusplus the deviation looks fine.

Fixed rt4 Item#nextPoint()

---

src/org/powerbot/script/rt6/Interactive.java
src/org/powerbot/script/rt6/Menu.java

Sometimes there are a lot of players in front of the entity you're trying to interact with and the client gets stuck in a continuous loop if the menu command is off-screen. You can still left-click it in this case.
This update checks the tooltip if you can still left-click the entity or not and fixes https://github.com/powerbot/powerbot/issues/1419.

Improved rt6 interactions, added tooltip menu command and some documentation

---

src/org/powerbot/script/rt4/ClientContext.java
src/org/powerbot/script/rt4/World.java
src/org/powerbot/script/rt4/Worlds.java

This World API allows users to select and filter possible worlds to join via the world switcher interface in Oldschool RuneScape. Here's an example:
``` java
ctx.worlds.open(); // Opens world switcher widget
ctx.worlds.select()
.joinable() // Selects and filters all worlds which are not PVP, DMM, or skill-required.
.types(Type.FREE) // Filters all worlds which are free
.servers(Server.NORTH_AMERICA) // Only filters down to north american servers
.population(1000) // Filters down to worlds with less than or equal to 1000 players on
ctx.worlds.peek().hop(); // Hops to the specified world
```

Add World API

---

src/main/java/org/powerbot/script/rt6/Bank.java
src/main/java/org/powerbot/script/rt6/Constants.java

- adds a `bank.close(boolean)` method, which allows the user to specify whether to use the hotkey or the mouse.
- keeps the default `bank.close()` as an overloaded method; returns `bank.close(false)` by default to keep all script behaviors the same.

added hotkey option to close bank

---

src/main/java/org/powerbot/script/rt4/Widgets.java

Deprecated original method. The new implementation includes some small delays to better mimick players looking for a component, and actually has the option to move the scroll bar by clicking rather than scrolling.

Added support for mouse and bar scrolling rt4

---

src/main/java/org/powerbot/script/rt4/CacheItemConfig.java
src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
src/main/java/org/powerbot/script/rt4/CacheObjectConfig.java

Parameters loading was added to rt4 cache definitions with a recent game update. This PR also adds some missing opcodes and adds item equip actions decoding.

Added new opcodes to rt4 cache reading

---

src/main/java/org/powerbot/bot/rt4/RandomEvents.java

random events can not be dismissed by the client if they occur when an
inventory item is selected, this will deselect the item if one is
selected

Fix random event dismissal

---

src/main/java/org/powerbot/script/rt4/World.java

Current implementation does not consider the chat you have to answer to enter PVP and high risk worlds, and also all worlds if the user hasn't disabled it. This may have been by choice to stop people entering PVP worlds by accident, but it should be up to the develop to select the right world rather than for the client to not support it by default.
Unsure if we should have a wait condition before checking ctx.chat.canContinue() but I believe this would work as is.
would fix #1757

Fix world hopping

---

src/main/java/org/powerbot/script/rt4/Bank.java

unlike rs3 osrs bank tabs only show the items in the tab, so if the user had a tab open when they last played and then starts a script - the script just dies if it requires banking
this checks the component is visible and if not then it opens tab 0 which will display all of the items in the bank

Failsafe if wrong bank tab is open

---

src/main/java/org/powerbot/script/rt4/Widgets.java

If the users bank is relatively empty (ie. not enough items to scroll) the bank attempts to scroll, but the scroll method returns false due to not being able to scroll. Potential fixes would be either to return true from the scroll method at this point, or just to check if you need to scroll in the bank method instead before calling it.
I chose this one as it seemed like it would be the best in case any other api methods have the same issue, this would resolve them all.

fix broken banking edge case

---

src/iDzn/ConstructUp/ConstructUp.java
src/iDzn/KegBalancer/Tasks/KegMe.java

The GameObject for the Keg was initialised at the start of the script causing it not to function if the keg was not valid when starting.

Correcting fix on KegBalancer

---

src/main/java/org/powerbot/script/rt4/Magic.java

[Screenshot](https://i.imgur.com/NMoxzvd.png) shows that the component isn't 406, the texture is 406 or 356 but the component is 1.

Home Teleport component update

---

src/main/java/org/powerbot/script/rt4/Game.java

There is a logic error in inViewport() : boolean where the upper x and y coordinates are not bounded in resizable mode. Points that are offscreen are being registered as being within the viewport even when they are not.
Current: 
Fixed:

Viewport logic fix

---

src/main/java/org/powerbot/bot/rt4/RandomEvents.java

fixes the bug when the telegrab spell is ready to cast and a random event pops up

Bugfix for telegrabbing wines

---

src/main/java/org/powerbot/bot/rt4/RandomEvents.java

Reverts powerbot/powerbot#1821
1. This does not compile;
2. Using hard-coded coordinates is not a proper solution;
3. This should be generalized to work for any pending spell cast;

Revert "Bugfix for telegrabbing wines"

---

src/main/java/org/powerbot/script/rt4/Worlds.java

This reverts commit 41a4340c32fff19a99ae65c75f87cafa239d9b02.
Making Worlds-specific filters return `IdQuery` disallows consumers of the API from chaining queries.

Revert "Correct types"

---

src/main/java/org/powerbot/script/rt4/Bank.java

The component number was changed from 33 to 32 in the latest update of the game, 33 now refers to a close button.

Update to component

---

src/main/java/org/powerbot/script/rt4/GameObject.java
src/main/java/org/powerbot/script/rt4/Objects.java
src/main/java/org/powerbot/script/rt6/GameObject.java
src/main/java/org/powerbot/script/rt6/Objects.java

Creates a static "NIL" instance that is lazy-loaded and used for `valid()` to improve validation speed.
99% of the time, when a script writer is calling `valid()`, they want to make sure it's not NIL. This does an additional, preliminary check that the object is not NIL.
Checking memory addresses is infinitely faster than a object query.

Faster valid checks for GameObjects

---

src/main/java/org/powerbot/script/rt6/Constants.java

Partially addresses #1832 
This puts the API back in a state of functionality, but does not support the recent updates to the bank.
1. RS3 now has 10 preset slots - we only support 2.
1. Every bank action has a default, corresponding keybind - none of which we support in the API.
1. There are new interfaces for different storage types which this does not address.
These and others may be addressed in future updates to the API.

Updated bank widgets to reflect changes

---

src/main/java/org/powerbot/script/rt4/DepositBox.java

The `get()` method would break whenever encountering an empty slot in the deposit box.
This caused the query to stop after encountering the first empty inventory slot. 
Replacing `break` with `continue` would have solved the issue. I clarified the logic a little more instead.
Fixes #1860

Fixed DepositBox get()

---

src/main/java/org/powerbot/bot/rt4/BankPin.java

If next digit is hovered (since numbers reposition every click) the bot can not find the one to click. Added code checks if it was found and clicked, if not it will move the mouse.
https://github.com/powerbot/powerbot/issues/1865

Fixes bank pin, rt4

---

src/main/java/org/powerbot/script/PollingScript.java

ClientContext has 6 PollingScripts which results in a poll every 360ms, the sleep is too long for each one so it should be reduced.

Reduce thread sleep

---

src/main/java/org/powerbot/script/rt4/Inventory.java

Adds functionality for finding points at various indices, also adds a function to get the boundingRectangle as well as offers dragging functionality for dragging an item to a certain index.
The boundingRectangle/point is off slightly during banking. This is because the default Inventory#component() changes for some reason, I'm not sure why. Widget 140 remains correct even during banking however it may be something I don't understand.
This resolves most of Issue #1886, and there's another commit that I believe has already been merged would resolve the rest of it. Which would end Issue #1886.

Adds dragging and indices to RT4.Inventory

---

src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java
src/main/java/org/powerbot/script/rt4/CacheObjectConfig.java

RT4 configs were updated to make them more consistent with each other. They now all have public methods for getting the Config via an id parameter. The classes themselves are all public with private/package-private constructors.

Updating CacheConfigs

---

src/main/java/org/powerbot/script/PollingScript.java

I believe majority of scripts are relying on the default #canBreak() thus it becomes a very bot-like thing when scripts only ever log out or pause after you have finished mining, or after you've finished fletching etc.
Since the new break handler will support actual breaks not just stops, it is much better if a user can pause mid-action. (i.e go checkout facebook while their character continues to cut a tree down).
Combat checks still remain, and a break will not engage during combat. However, if you are close to aggressive monsters you should be overriding canBreak yourself!

remove animation check for default break

---

src/main/java/org/powerbot/script/rt4/Game.java

Added a check to ensure that the key is not empty. Before this patch, the code would still try to send an empty key just because the tab existed.

Fixes tab with empty key assigned

---

src/main/java/org/powerbot/script/Area.java

Currently, we are experiencing issues using the contains method.
```
public static void main(String[] args) {
Area area = new Area(new Tile(0,0), new Tile(2,2));
System.out.println(area.contains(new Tile(0,0))); // true as expected
System.out.println(area.contains(new Tile(0,1))); // true as expected
System.out.println(area.contains(new Tile(1,0))); // true as expected
System.out.println(area.contains(new Tile(2,2))); // false <-- This is the problem
System.out.println(area.contains(new Tile(0,4))); // false as expected
System.out.println(area.contains(new Tile(4,0))); // false as expected
}
```
The current `contains` method doesn't account for the Oracle [Definition of insideness](https://docs.oracle.com/javase/8/docs/api/java/awt/Shape.html#def_insideness) for points on the upper …

Implements containsOrIntersects method for Area

---

src/main/java/org/powerbot/script/rt6/ProductionInterface.java

For `makeItem(), it uses the `START_BUTTON_COMPONENT ` component.
Component 20 is something else:
Component 12 is proper:

Fix ProductionInterface component id

---

src/main/java/org/powerbot/script/rt4/Actor.java

inCombat was very confusing for new people as its name is unintuitive unless you read the documentation. Deprecating it will discourage its use, and adding the new healthBarVisible method will still allow people to use the functionality when needed

Deprecate inCombat refactor into a new method

---

src/main/java/org/powerbot/script/rt4/Worlds.java

Closes #2031
Update has changed worlds list so filter component is always visible.
World list component is no longer a fixed height.
There's another component which does not contain world details, is the exact same dimensions as correct component and has 600 sub components.
New list contains 1092 sub components, but is subject to change as worlds are added or removed.
Hence I chose 800 to filter the correct component.

Update osrs worlds list

---

src/main/java/org/powerbot/script/rt4/Prayer.java

Updated correct prayer indexes.
Refactored to use quickSelectionIndex rather than ordinal() which is highly unintuitive and inflexible.
Also tested cases where effect.quickSelectIndex() was used for setting up quick prayers and seems good.
In the quick prayer setup interface, the component indexes of the prayers match the varpbit offset to check if the prayer is active.
In the normal prayer interface, the component indexes follow a different ordering.

Update prayer Effect

---

src/main/java/org/powerbot/script/rt4/World.java
src/main/java/org/powerbot/script/rt4/Worlds.java

Fixing world list scrolling by adding a new method to get the viewport.
I didn't realise the world list was also being used as the scroll viewport. The new list is now > 2000 pixels high and doesn't work for scrolling.

Fix viewport for world list scrolling

---

src/main/java/org/powerbot/script/rt4/Chat.java

The level up prompt offsets the continue component depending on how many new items you are able to make.
The constant {11, 3} would not have worked in this case as the continue component was offset to the 4th component.
Although I don't ever recall the text being different, if the "Click here to continue" text is different somewhere, this will break.
https://i.imgur.com/lYIHPmk.png

Change chat getContinue to use component query

---

src/main/java/org/powerbot/script/ClientContext.java

The method getPin was returning null as the property requested didn't exist. account.<user_id>.pin was changed to login.<user_id>.pin in one of the PRs. Artifact with bugfix was tested by creator of #2084 .

Fixes getPin

---

src/main/java/org/powerbot/bot/cache/JagexStream.java
src/main/java/org/powerbot/script/rt4/CacheNpcConfig.java

This a temporary patch for deformed cache payloads for Npcs. Affected entities will have a string literal "null" as their name, but IDs work fine. Note that the vast majority of Npcs are not affected by this.

temporary workaround for deformed cache NPCs

---

src/main/java/org/powerbot/script/rt4/Bank.java

The default implementation of `interact` uses a Filter that checks for string contains rather than equals. 
This is an issue if the user's Withdraw-X quantity contains any of the preset values (1, 5, 10) since this will cause it to select the wrong withdraw amount.

Fix withdraw x

---

src/main/java/org/powerbot/script/rt4/Bank.java
src/main/java/org/powerbot/script/rt4/Game.java
src/main/java/org/powerbot/script/rt4/Menu.java

This makes a couple of changes to the Bank API to add additional useful methods and clean up some of the methods.
- Adds an overload to `close` to support closing by using the ESC key;
- the default implementation was kept to use the close button
- Adds a helper method `game.settings.escClosingEnabled()` to check if the user has ESC interface closing enabled in their settings;
- Adds overloads to `withdraw` to support withdrawing by name and Filter;
- Adds `withdrawAmount` that withdraws items from the bank and returns the number the items withdrawn;
- Added a couple helper methods to get the withdraw logic down from 61 lines to 23 and to reduce some duplicate code between depositing and withdrawing;
- Refactored existing `withdraw` method to return `withdrawnAmount() > 0` to keep its …

Bank improvements

---

src/main/java/org/powerbot/script/rt4/BasicQuery.java

Method references and generics don't play well together. Replacing the lambda with a method reference causes an exception to be thrown since the type cannot be correctly inferred. 
Fixes #2119

replace method reference with explicit lambda.

---

src/main/java/org/powerbot/bot/rt4/TLoginState.java
src/main/java/org/powerbot/script/rt4/Constants.java
src/main/java/org/powerbot/script/rt4/Game.java

- adds support for Login State debugging in client view
- adds user setting for allowing/disallowing PVP worlds
- adds support for handling Login State 1: PVP World Warning Message
- if user does not enable "Allow PVP Worlds" then script stops at this state
Fixes https://github.com/powerbot/RSBot-API/issues/2124

Merge bug/2124-pvp-login-state to master

---

src/main/java/org/powerbot/script/rt4/Bank.java

Not all noted items are id+1, so this removes the ID check entirely and instead waits for any change in the inventory. Since you can't withdraw multiple items simultaneously this should be fine. 
Fixes #2134

removes ID check from bank withdraw condition

---

src/main/java/org/powerbot/script/rt4/Game.java

The option for bottomLineTabs does not affect fixed mode but was still being considered.

Fix openedTabIndexOffset

---

src/main/java/org/powerbot/script/rt4/Equipment.java

the required component data are loaded in regardless of the component being visible. With previous code ring and quiver items would return nil if you weren't looking at the component even thought they had valid data

removed redundant code

---

src/main/java/org/powerbot/script/rt4/Equipment.java

Equipment widget does not always load correctly -> leading to invalid query results when not on the equipment tab

reverse Redundant code

---

src/main/java/org/powerbot/script/rt4/LocalPath.java

Safe to expose, means we can access the underlying tilepath for various use (eg drawing the projected route)

Exposes tilePath on LocalPath.

---

src/main/java/org/powerbot/script/rt4/Actor.java
src/main/java/org/powerbot/script/rt4/BoundingModel.java
src/main/java/org/powerbot/script/rt4/GameObject.java
src/main/java/org/powerbot/script/rt4/Model.java
src/main/java/org/powerbot/script/rt4/Npc.java

The default cuboid bounding model will be used in case the cache model
fails to load. Additionally, if a custom bounding model is set by the
script writer, it will be used instead of the relevant cache model.

Allow npc and object interactions to rely on cache models

---

src/main/java/org/powerbot/script/rt4/Npc.java

Without NPC model animations, nextPoint can cause inViewport to wrongly
return true. Using centerPoint instead remedies this.

Use model center point to check for NPC visibility

---

src/main/java/org/powerbot/script/rt4/CacheComponentConfig.java
src/main/java/org/powerbot/script/rt4/Component.java
src/main/java/org/powerbot/script/rt4/Widget.java

Accessible through `Widget` and thus indirectly through `Component`.
`Widget` loads configs for its child components that they in turn can access with their indices.
E.g.
`ctx.widgets.widget(1).component(2).cacheConfig()`
or
`ctx.widgets.widget(1).cacheConfigs()[child_index]`

Add cache component loader

---

src/main/java/org/powerbot/script/rt4/Bank.java

The `Set.of` method allows one to create an unmodifiable set from an array without having to instantiate two intermediate objects. Thus, using it is more concise and also more performant. 😊

Use the Set.of method introduced in Java 9
